name: Build TUI-ConsoleLauncher APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          ./gradlew clean assembleFdroidDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TUI-ConsoleLauncher-debug-apk
          path: app/build/outputs/apk/fdroid/debug/*.apk
