name: Build TUI-ConsoleLauncher APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build F-Droid Debug APK
        run: ./gradlew clean assembleFdroidDebug

      - name: Build Normal Debug APK
        run: ./gradlew assembleNormalDebug

      - name: Upload F-Droid APK
        uses: actions/upload-artifact@v4
        with:
          name: TUI-ConsoleLauncher-fdroid-apk
          path: app/build/outputs/apk/fdroid/debug/*.apk

      - name: Upload Normal APK
        uses: actions/upload-artifact@v4
        with:
          name: TUI-ConsoleLauncher-normal-apk
          path: app/build/outputs/apk/normal/debug/*.apk
